src/components/auth/SignInCard.tsx
src/components/auth/SignInLogo.tsx
src/pages/SignIn.tsx

Changed the title on the Sign In page from "Sign in" to "Sign in to Staging Site" to reflect the staging environment. [skip gpt_engineer]

Update Sign In page title

---

src/components/site-config/BlogContent.tsx
src/components/site-config/BlogSection.tsx

Resolved the import issue in `src/components/site-config/BlogSection.tsx` where `BlogSection` was not exported correctly. This change ensures that the component can be imported and used without causing build errors. [skip gpt_engineer]

Fix import error in BlogSection.tsx

---

src/components/site-config/nav/AuthButtons.tsx
src/routes/AppRoutes.tsx

Updated the login and signup page URLs to point to www.limitlesslab.org/login and www.limitlesslab.org/signin, while ensuring that all dashboard routes remain under app.limitlesslab.org. [skip gpt_engineer]

Change login and signup URLs

---

src/components/auth/useAuthRedirect.ts
src/pages/SignIn.tsx

Addressed an issue causing an infinite redirect loop between the sign-in pages on different domains. Adjustments made to the authentication flow to ensure proper domain handling and prevent repeated redirects. [skip gpt_engineer]

Fix infinite redirect loop

---

src/App.tsx
src/components/auth/useAuthRedirect.ts
src/pages/SignIn.tsx

Resolved the redirect loop between limitlesslab.org and app.limitlesslab.org to ensure proper navigation and user experience. [skip gpt_engineer]

Fix redirect loop issue

---

src/components/signup/SignupSteps.tsx

Addressed various errors encountered in the codebase. Further investigation may be required to identify specific issues and implement appropriate fixes. [skip gpt_engineer]

Fix errors in codebase

---

src/components/auth/useAuthRedirect.ts
src/components/signup/SignupSteps.tsx

Changed the redirect link for email verification to ensure users are redirected to the dashboard for onboarding after verification. [skip gpt_engineer]

Update email verification redirect link

---

src/components/signup/SignupSteps.tsx

Updated the confirmation link for account verification to include the correct token and redirect URL. [skip gpt_engineer]

Update email verification link

---

src/components/signup/SignupSteps.tsx

Refactor existing code to improve readability and maintainability. No functional changes were made; the focus was on organizing the codebase more effectively. [skip gpt_engineer]

Update code structure and organization

---

src/components/invite/InviteModal.tsx
src/components/invite/InvitedUserOnboardingModal.tsx

Investigate and resolve the issue causing invited users to encounter a "User Not Found" error after setting their password and completing the onboarding process. [skip gpt_engineer]

Fix user not found error on invite

---

src/components/auth/useAuthRedirect.ts
src/components/invite/InviteModal.tsx
src/components/invite/hooks/useInviteSubmit.ts

Refactor the invite user flow to:
1. Confirm email before proceeding.
2. Allow users to set their password, marking them as confirmed.
3. Automatically sign up the user to the invited workspace in the background.
4. Redirect users to the sign-in page after setting their password.
5. Prompt users to sign in.
6. Direct users to their dashboard with the invited workspace.
7. Remove onboarding popup for invited users. [skip gpt_engineer]

Update Invite User Flow

---

src/components/auth/useAuthRedirect.ts
src/components/invite/hooks/useInviteSubmit.ts
src/components/layout/ProfileMenu.tsx
src/components/onboarding/OnboardingModal.tsx
src/pages/InvitePage.tsx

Addressed issue where invited users' workspaces were not loading upon login. Ensured onboarding form is displayed correctly for these users. [skip gpt_engineer]

Fix login for invited users

---

index.html
src/components/common/SEO.tsx
src/main.tsx
src/pages/landing/Services.tsx

Audits the code to identify and resolve issues causing incorrect social media previews.

Audit social media preview

---

index.html
src/components/common/SEO.tsx

The SEO component was not updating correctly.

Address SEO component issue

---

src/components/blog/BlogSchemaGenerator.tsx
src/components/common/SEO.tsx
src/hooks/useBlogPostSEO.ts
src/hooks/useMetaTags.ts
src/hooks/usePageSEO.ts

- Ensure correct image URLs and sizes for social media.
- Implement cache-busting for images.
- Add article-specific meta tags.
- Use validation tools and clear caches.

Fix: Improve SEO meta tag handling

---

index.html
src/pages/Index.tsx
src/pages/ToolDetails.tsx
src/pages/landing/ToolDetail.tsx
src/pages/landing/Tools.tsx

Remove OpenGraph meta tags from the codebase.

Remove OpenGraph settings

---

index.html
src/integrations/supabase/types.ts
src/pages/BlogPost.tsx
src/pages/landing/Blog.tsx

Set og:title to the blog post title, og:image to the cover image, and og:description to the excerpt.

Fix: Implement Open Graph tags for blog posts

---

src/pages/BlogPost.tsx
src/pages/CaseStudy.tsx
src/pages/landing/Blog.tsx
src/pages/landing/CaseStudies.tsx

Ensure page-specific OpenGraph tags are used for blog posts and case studies.

Fix: OpenGraph meta tags

---

src/pages/BlogPost.tsx

The error "Rendered more hooks than during the previous render" is resolved.

Fix: Resolve "Rendered more hooks" error

---

src/pages/BlogPost.tsx
src/pages/CaseStudy.tsx
src/pages/landing/Blog.tsx

Refactor OpenGraph tags to dynamically generate based on page content, resolving incorrect metadata issues.

Fix: Revamp OpenGraph tags for blog pages

---

index.html
package-lock.json
package.json
src/App.tsx
src/components/common/OpenGraphTags.tsx
src/pages/BlogPost.tsx
src/pages/CaseStudy.tsx
src/pages/landing/Blog.tsx

This commit implements the blog post and case study pages, including fetching data, displaying content, and handling errors. It also includes SEO optimizations such as meta tags and OpenGraph tags.

Implement blog post and case study pages

---

src/components/admin/blog/BlogForm.tsx
src/components/admin/blog/components/BlogFormContent.tsx
src/components/admin/blog/hooks/useBlogFormSubmit.ts
src/constants/blogCategories.ts

The meta_description field should be populated with the excerpt value. Also, implement a fixed set of categories for the blog post.

Fix: Blog post meta description

---

src/components/onboarding/OnboardingModal.tsx
src/components/signup/SignupSteps.tsx
src/pages/SignUp.tsx
supabase/functions/handle-systeme-signup/index.ts

Fixes an issue where new user signups were failing.

Fix: Signup not working

---

src/components/onboarding/OnboardingModal.tsx
src/components/workspace/CreateWorkspaceDialog.tsx

Audit and fix issues related to onboarding and workspace selection to ensure correct flow.

Fix: Onboarding and workspace selection issues

---

src/components/onboarding/OnboardingModal.tsx
src/components/onboarding/hooks/useOnboardingSubmit.ts
src/pages/Dashboard.tsx
src/pages/SignIn.tsx
src/pages/SignUp.tsx

Conditionally render the workspace creation step in the onboarding flow based on whether the user is invited.

Fix: Onboarding flow for invited users

---

index.html
package-lock.json
src/App.tsx
src/components/auth/useAuthRedirect.ts
src/components/lessons/VideoPlayer.tsx
src/components/onboarding/OnboardingModal.tsx
src/pages/SignIn.tsx

CHANGES: 
- Fixed black screen caused by the mailing provider
- Fixed React Video player error caused by improper scripting
- Fixed images being shown cause by improper scripting

fix: deployment bugs fixed

---

server-middleware.js
src/App.tsx
src/components/auth/ForgotPasswordForm.tsx
src/components/auth/RequireAuth.tsx
src/components/auth/SignInForm.tsx
src/main.tsx
src/pages/ResetPassword.tsx
src/routes/AppRoutes.tsx

UPDATE:
- Now sends an email link to the user
- Redirects the valid user to the reset password form page

fix: password reset functionality

---

src/components/admin/workspaces/WorkspaceHeader.tsx
src/components/invite/InviteModal.tsx
src/components/invite/hooks/useInviteSubmit.ts
src/components/invite/steps/InviteSignIn.tsx
src/components/layout/WorkspaceSelector.tsx
src/components/onboarding/OnboardingModal.tsx
src/components/onboarding/hooks/useOnboardingSubmit.ts
src/components/settings/GeneralSettings.tsx
src/components/settings/MembersSettings.tsx
src/components/settings/WorkspaceForm.tsx
src/components/settings/members/InviteMemberDialog.tsx
src/components/settings/members/useMembers.ts
src/components/workspace/WorkspaceList.tsx
src/hooks/useWorkspaceRole.ts
src/pages/Dashboard.tsx
src/pages/SignIn.tsx
src/pages/SignUp.tsx
src/pages/admin/AdminUsers.tsx
src/pages/admin/AdminWorkspaceDetails.tsx
src/pages/admin/courses/tabs/CourseWorkspaces.tsx
supabase/functions/admin-delete-user/index.ts
supabase/functions/process-invitation-acceptance/index.ts
supabase/functions/send-workspace-invite/index.ts
supabase/functions/verify-invitation/index.ts

UPDATE:
- Users can now invite members on their workspaces thru email.
- Admin can now properly delete users from the admin panel.
- Added new sign in form for newly invited users to the platform.
FIX: 
- Fixed bug where new users need to create workspace TWICE.

fix: workspace invitation
